In [85]:
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from scipy.optimize import curve_fit
output_notebook()

Loading BokehJS ...

In [86]:
np.random.seed(3)

In [147]:
def math_function(data,a,b):
    data = a * np.sin(2 * np.pi * data[0]) + b * np.cos(2 * np.pi * data[1])
    return data

def math_functionc(data,a,b):
    return data[0] * a + data[1] * b

In [160]:
x_range = np.arange(-2,2,.05)
y_range = np.arange(-2,2,.05)
x, y = np.meshgrid(x_range, y_range)
a = .1
b = .2
c = .3
d = .4
z_practice = math_function((x,y),a,b)
z_practice = z_practice + np.random.normal(loc=0, scale=.02, size=z_practice.shape)
print(x,y,z_practice,sep='\n~~~~~~~~~~~~~~\n')
print("***********")
print(x.flatten(),y.flatten(),z_practice.flatten(),sep='\n~~~~~~~~~~~~~~\n')

[[-2.   -1.95 -1.9  ...  1.85  1.9   1.95]
 [-2.   -1.95 -1.9  ...  1.85  1.9   1.95]
 [-2.   -1.95 -1.9  ...  1.85  1.9   1.95]
 ...
 [-2.   -1.95 -1.9  ...  1.85  1.9   1.95]
 [-2.   -1.95 -1.9  ...  1.85  1.9   1.95]
 [-2.   -1.95 -1.9  ...  1.85  1.9   1.95]]
~~~~~~~~~~~~~~
[[-2.   -2.   -2.   ... -2.   -2.   -2.  ]
 [-1.95 -1.95 -1.95 ... -1.95 -1.95 -1.95]
 [-1.9  -1.9  -1.9  ... -1.9  -1.9  -1.9 ]
 ...
 [ 1.85  1.85  1.85 ...  1.85  1.85  1.85]
 [ 1.9   1.9   1.9  ...  1.9   1.9   1.9 ]
 [ 1.95  1.95  1.95 ...  1.95  1.95  1.95]]
~~~~~~~~~~~~~~
[[0.18108872 0.22767595 0.29328744 ... 0.11041496 0.12185559 0.21880409]
 [0.17236833 0.2121361  0.25745    ... 0.1039648  0.10370643 0.13143006]
 [0.17295229 0.19520283 0.20090825 ... 0.07630472 0.14032603 0.09450509]
 ...
 [0.14410361 0.12451725 0.17107646 ... 0.06048451 0.03580973 0.08555431]
 [0.17492009 0.1674577  0.19664253 ... 0.09464735 0.09086666 0.13227633]
 [0.16114725 0.22282067 0.22609442 ... 0.10336723 0.14249849 0.12620256]

In [161]:
p = figure(plot_width=600, plot_height=300, output_backend="webgl")
p.circle(x[0],z_practice[0],radius=.01)
show(p)

In [162]:
%%timeit
popt, pcov = curve_fit(math_function,(x.flatten(),y.flatten()),z_practice.flatten())

# print(popt, "\n",pcov)

6.76 ms ± 582 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


array([-7.40808398e-04,  9.73990053e-01,  1.26396793e-02,  9.24700173e-01])

In [77]:
def f((a,b),c):
    print(a,b,c)

SyntaxError: invalid syntax (<ipython-input-77-3dbaf3226b7b>, line 1)